#!/usr/bin/env php
<?php
error_reporting(E_ALL | E_STRICT);

require_once 'lib/Output.php';
require_once 'lib/FeatureParser.php';
require_once 'lib/StepExecutor.php';

$parser = new FeatureParser("features/albums.feature");
$parser->parse();
?>
